import json
import pySBOLx
import unittest

from XplanDataParser import XplanDataParser

import xplan_to_sbol.__main__ as xbol
from sbol import *

''' 
	This module is used to test data generated from xplan to sbol for the rule of 30 challenge problem.
	
	author(s) : Tramy Nguyen
''' 

class TestRule30(unittest.TestCase):
	
	""" 
	This class will perform unit testing on the rule of 30 example that was generated by xplan2sbol converter.

	There are 2 options to run this test module:
		1. Run this module independently from other test modules: python -m unittest TestRule30.py
		2. Run this module as a test suite: python tests/SBOLTestSuite.py
	"""
	@classmethod
	def setUpClass(cls):
		print("Running " + cls.__name__)
		rule30_json = 'example/xplan/rule30-Q0-v2.json'
		rule30_sbol = 'example/sbol/rule30-Q0-v2.xml'
		
		cls.sbolDoc = Document()
		cls.sbolDoc.read(rule30_sbol)
		
		with open(rule30_json) as jsonFile:
				jsonData = json.load(jsonFile)
				cls.xplan_data = XplanDataParser(jsonData)

	def test_Activities_Props(self):

		PURL_NS = 'http://purl.org/dc/terms/'
		TITLE_NS = PURL_NS + 'title'
		
		for a in self.sbolDoc.activities:
			print(a)